# Generated by Django 5.2.4 on 2025-07-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_phone_country_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
