# Generated by Django 5.2.4 on 2025-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_update_kyc_document_type_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(max_length=50, choices=[
                ('government_id_us_drivers_license', 'U.S. Driver\'s License'),
                ('government_id_us_state_id', 'U.S. State-issued ID'),
                ('government_id_us_passport', 'U.S. Passport'),
                ('government_id_passport', 'International Passport'),
                ('government_id_national_id', 'National ID Card'),
                ('government_id_drivers_license', 'Driver\'s License (Non-U.S.)'),
                ('proof_address_utility_bill', 'Utility Bill (Water/Electricity/Gas)'),
                ('proof_address_bank_statement', 'Bank Statement'),
                ('proof_address_credit_card_statement', 'Credit Card Statement'),
                ('proof_address_lease_agreement', 'Lease/Rental Agreement'),
                ('proof_address_mortgage_statement', 'Mortgage Statement'),
                ('proof_address_government_mail', 'Government Correspondence'),
                ('tax_us_ssn_card', 'Social Security Card'),
                ('tax_us_w2_form', 'W-2 Tax Form'),
                ('tax_us_form_1040', 'Form 1040 (Tax Return)'),
                ('tax_us_w9_form', 'W-9 Form'),
                ('tax_international_tin', 'Tax Identification Number'),
                ('tax_international_return', 'Foreign Tax Return'),
                ('verification_selfie_with_id', 'Selfie with ID Document'),
                ('employment_verification', 'Employment Verification Letter'),
                ('income_proof', 'Proof of Income Document'),
                # Legacy document types for backward compatibility
                ('drivers_license', 'Driver\'s License'),
                ('passport', 'Passport'),
                ('national_id', 'National ID Card'),
                ('utility_bill', 'Utility Bill'),
                ('bank_statement', 'Bank Statement'),
                ('lease_agreement', 'Lease Agreement'),
                ('ssn_card', 'Social Security Card'),
                ('w2_form', 'W-2 Tax Form'),
                ('form_1040', 'Form 1040'),
                ('selfie_with_id', 'Selfie with ID'),
            ]),
        ),
    ]
