# Generated by Django 5.2.4 on 2025-07-09 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('fixed_deposit', 'Fixed Deposit'), ('foreign_currency', 'Foreign Currency Account'), ('joint', 'Joint Account'), ('corporate', 'Corporate Account')], default='savings', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('hold_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15)),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=500000.0, max_digits=15)),
                ('monthly_transaction_limit', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('monthly_maintenance_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('dormant', 'Dormant')], default='active', max_length=20)),
                ('account_officer', models.CharField(blank=True, max_length=200)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('purpose_of_account', models.TextField(blank=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=200)),
                ('is_joint_account', models.BooleanField(default=False)),
                ('requires_two_signatures', models.BooleanField(default=False)),
                ('allow_online_transactions', models.BooleanField(default=True)),
                ('allow_international_transactions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('percentage_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_primary', models.BooleanField(default=False)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Account Beneficiary',
                'verbose_name_plural': 'Account Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('login_successful', models.BooleanField(default=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'International Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card")], max_length=20)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('work_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('customer_tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP'), ('corporate', 'Corporate')], default='standard', max_length=20)),
                ('account_officer', models.CharField(blank=True, max_length=200)),
                ('preferred_branch', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(default='pending', max_length=20)),
                ('risk_profile', models.CharField(default='low', max_length=20)),
                ('pep_status', models.BooleanField(default=False)),
                ('aml_check_status', models.CharField(default='pending', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('statement_delivery', models.CharField(default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kyc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('mother_maiden_name', "What is your mother's maiden name?"), ('first_pet_name', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('first_school', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?'), ('childhood_nickname', 'What was your childhood nickname?')], max_length=50)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Question',
                'verbose_name_plural': 'Security Questions',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
