# Generated by Django 5.2.4 on 2025-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_enhanced_kyc_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternative_phone_country',
            field=models.CharField(blank=True, help_text='Country code for alternative phone', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_country',
            field=models.CharField(default='US', help_text='Country code for phone number', max_length=5),
        ),
    ]
