# Generated by Django 5.2.4 on 2025-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_accountnotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
    ]
