# Generated by Django 5.2.4 on 2025-07-09 09:55

import accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('documents_required', 'Documents Required'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info_required', 'Additional Information Required')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity_document', 'Identity Document'), ('proof_of_address', 'Proof of Address'), ('employment_verification', 'Employment Verification'), ('income_statement', 'Income Statement'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('tax_document', 'Tax Document'), ('signature_specimen', 'Signature Specimen'), ('passport_photo', 'Passport Photo'), ('other', 'Other Document')], max_length=30)),
                ('document_name', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to=accounts.models.kyc_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_resubmission', 'Requires Resubmission')], default='pending', max_length=25)),
                ('is_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user_profile', 'document_type')},
            },
        ),
    ]
