# Generated by Django 5.2.4 on 2025-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='politically_exposed_person',
            field=models.BooleanField(default=False, help_text='Are you a Politically Exposed Person?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='source_of_funds',
            field=models.CharField(blank=True, help_text='Primary source of funds', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, help_text='Social Security Number (XXX-XX-XXXX)', max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ssn_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('identity_document', 'Identity Document'), ('proof_of_address', 'Proof of Address'), ('ssn_card', 'Social Security Card'), ('w2_form', 'W-2 Form'), ('1099_form', '1099 Form'), ('tax_return', 'Tax Return'), ('employment_verification', 'Employment Verification'), ('income_statement', 'Income Statement'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('signature_specimen', 'Signature Specimen'), ('selfie_with_id', 'Selfie with ID'), ('other', 'Other Document')], max_length=30),
        ),
    ]
