# Generated by Django 5.2.4 on 2025-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_kyc_document_type_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transfer_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed 4-digit transfer PIN', max_length=255),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('government_id_us_drivers_license', "U.S. Driver's License"), ('government_id_us_state_id', 'U.S. State-issued ID'), ('government_id_us_passport', 'U.S. Passport'), ('government_id_passport', 'International Passport'), ('government_id_national_id', 'National ID Card'), ('government_id_drivers_license', "Driver's License (Non-U.S.)"), ('proof_address_utility_bill', 'Utility Bill (Water/Electricity/Gas)'), ('proof_address_bank_statement', 'Bank Statement'), ('proof_address_credit_card_statement', 'Credit Card Statement'), ('proof_address_lease_agreement', 'Lease/Rental Agreement'), ('proof_address_mortgage_statement', 'Mortgage Statement'), ('us_ssn_card', 'Social Security Number (SSN) Card'), ('us_itin_letter', 'IRS ITIN Letter'), ('us_w2_form', 'W-2 Tax Form'), ('us_1099_form', '1099 Tax Form'), ('us_tax_return', 'U.S. Tax Return'), ('selfie_with_id', 'Selfie with Government ID'), ('employment_verification', 'Employment Verification Letter'), ('income_statement', 'Income Statement/Pay Stub'), ('birth_certificate', 'Birth Certificate'), ('other_supporting', 'Other Supporting Document')], max_length=50),
        ),
    ]
