# Generated by Django 5.2.4 on 2025-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_transaction_business_days_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='aml_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='beneficiary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='beneficiary_country',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='external_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='network_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='network_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='network_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='ofac_screening_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='purpose_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_routing_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='to_swift_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Internal Transfer'), ('domestic', 'Domestic Transfer'), ('domestic_external', 'Domestic External Transfer'), ('international', 'International Transfer')], default='internal', max_length=20),
        ),
    ]
