# Generated by Django 5.2.4 on 2025-07-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_remove_transaction_aml_risk_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='status',
        ),
    ]
