# Generated by Django 5.2.4 on 2025-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_remove_depositrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card used', max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External reference ID from third-party processors', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose_code',
            field=models.CharField(blank=True, help_text='Transaction purpose code for regulatory compliance', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(blank=True, help_text='Recipient account number', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_bank_name',
            field=models.CharField(blank=True, help_text='Recipient bank name', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Name of the recipient (for external transfers)', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Bank routing number for external transfers', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_message',
            field=models.TextField(blank=True, help_text='Detailed status message for user display'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=11),
        ),
    ]
