# Generated by Django 5.2.4 on 2025-07-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='business_days_delay',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmation_method',
            field=models.CharField(choices=[('manual', 'Manual Confirmation'), ('auto', 'Automatic Confirmation'), ('instant', 'Instant Confirmation')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmation_required_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processing_delay_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='processing_delay_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TransactionConfirmationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_by', models.CharField(max_length=200)),
                ('confirmation_method', models.CharField(max_length=50)),
                ('confirmation_reason', models.TextField(blank=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_logs', to='banking.transaction')),
            ],
            options={
                'verbose_name': 'Transaction Confirmation Log',
                'verbose_name_plural': 'Transaction Confirmation Logs',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
