# Generated by Django 5.2.4 on 2025-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transaction_failed_at_transaction_failed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='aml_risk_score',
            field=models.IntegerField(blank=True, help_text='AML risk score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_address',
            field=models.TextField(blank=True, help_text='Beneficiary address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_country',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='Beneficiary full name', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='compliance_notes',
            field=models.TextField(blank=True, help_text='Compliance and regulatory notes'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Currency exchange rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External processor reference', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='External network processing fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network_response',
            field=models.JSONField(blank=True, default=dict, help_text='Network processor response'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='network_status',
            field=models.CharField(blank=True, help_text='ACH/SWIFT network status', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ofac_screening_status',
            field=models.CharField(default='pending', help_text='OFAC sanctions screening status', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose_code',
            field=models.CharField(blank=True, help_text='Transaction purpose code', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account_number',
            field=models.CharField(blank=True, help_text='External account number', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_bank_code',
            field=models.CharField(blank=True, help_text='Beneficiary bank code', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_bank_name',
            field=models.CharField(blank=True, help_text='Beneficiary bank name', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=34),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_routing_number',
            field=models.CharField(blank=True, help_text='ACH routing number', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_swift_code',
            field=models.CharField(blank=True, help_text='SWIFT BIC code', max_length=11),
        ),
    ]
