# Generated by Django 5.2.4 on 2025-07-24 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_transfer_pin_hash_and_more'),
        ('banking', '0006_transaction_aml_risk_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='aml_risk_score',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='approval_required',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary_country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='business_days_delay',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='compliance_notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmation_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmation_required_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='failed_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account_balance_after',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account_balance_before',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='network_fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='network_response',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='network_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ofac_screening_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='processing_delay_hours',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purpose_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account_balance_after',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account_balance_before',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_bank_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_bank_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_iban',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_routing_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_swift_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='aml_risk_score',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='beneficiary_country',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='compliance_notes',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='expected_completion_date',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='network_fee',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='network_response',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='network_status',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='ofac_screening_status',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='processing_delay_days',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='purpose_code',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='to_bank_code',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='to_iban',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='transfer_fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='auto_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmation_delay_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_reference',
            field=models.CharField(blank=True, help_text='External reference for deposit (check number, wire ref, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_source',
            field=models.CharField(blank=True, choices=[('cash', 'Cash Deposit'), ('check', 'Check Deposit'), ('wire', 'Wire Transfer'), ('ach', 'ACH Transfer'), ('mobile_check', 'Mobile Check Deposit'), ('direct_deposit', 'Direct Deposit'), ('atm', 'ATM Deposit'), ('branch', 'Branch Deposit'), ('other', 'Other')], help_text='Source of deposit funds', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_account_number',
            field=models.CharField(blank=True, help_text='Account number of the depositor (for wire/ACH deposits)', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_bank_name',
            field=models.CharField(blank=True, help_text='Bank name of the depositor (for external deposits)', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositor_name',
            field=models.CharField(blank=True, help_text='Name of person making deposit (if different from account holder)', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance after transaction for source account', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance before transaction for source account', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance after transaction for destination account', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance before transaction for destination account', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(choices=[('online', 'Online Banking'), ('mobile', 'Mobile Banking'), ('atm', 'ATM'), ('branch', 'Branch')], default='online', help_text='Channel through which transaction was initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, help_text='Source account for withdrawals/transfers. Leave null for deposits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='Destination account for deposits/transfers. Leave null for withdrawals.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('payment', 'Payment'), ('fee', 'Fee'), ('interest', 'Interest'), ('reversal', 'Reversal'), ('charge', 'Service Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='beneficiary_address',
            field=models.TextField(blank=True, help_text='Required for international transfers'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='Beneficiary full name', max_length=200),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Transfer description or purpose'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_to_account', to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_account_number',
            field=models.CharField(help_text='Destination account number', max_length=50),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_bank_name',
            field=models.CharField(blank=True, help_text='Destination bank name', max_length=200),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_routing_number',
            field=models.CharField(blank=True, help_text='ACH routing number', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_swift_code',
            field=models.CharField(blank=True, help_text='SWIFT BIC code', max_length=11),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Internal Transfer'), ('domestic_external', 'Domestic External Transfer'), ('international', 'International Transfer')], default='internal', max_length=20),
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_source', models.CharField(choices=[('cash', 'Cash Deposit'), ('check', 'Check Deposit'), ('wire', 'Wire Transfer'), ('ach', 'ACH Transfer'), ('mobile_check', 'Mobile Check Deposit'), ('direct_deposit', 'Direct Deposit'), ('atm', 'ATM Deposit'), ('branch', 'Branch Deposit'), ('other', 'Other')], max_length=20)),
                ('deposit_reference', models.CharField(blank=True, help_text='Check number, wire reference, etc.', max_length=100)),
                ('depositor_name', models.CharField(help_text='Name of person/entity making deposit', max_length=200)),
                ('depositor_account_number', models.CharField(blank=True, help_text='External account number (for wire/ACH)', max_length=50)),
                ('depositor_bank_name', models.CharField(blank=True, help_text='External bank name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the deposit')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deposits', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to='accounts.bankaccount')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.transaction')),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TransactionConfirmationLog',
        ),
    ]
